# yaml-language-server: $schema=https://raw.githubusercontent.com/kjanat/actionlint/refs/tags/v1.17.0/actionlint.schema.json
config-variables: []
config-secrets: []
policy:
  disallow-suppressions: true
  require-commit-hash: true
  require-job-timeout: true
