merge_protections:
  - name: renovate/artifacts
    if:
      - head *= renovate/*
    success_conditions:
      - check-success = renovate/artifacts
  - name: workflow-lint
    if: []
    success_conditions:
      - check-success = workflow-lint
  - name: ci
    if: []
    success_conditions:
      - check-success = git-check
      - check-success = pnpm-run-lint
