name: Reovate commit status check
description: Checks renovate commit statuses
runs:
  using: composite
  steps:
    - if: startsWith(github.head_ref, 'renovate/')
      uses: actions/github-script@v9.0.0
      with:
        script: |
          const ref = context.payload.pull_request.head.ref.substring('renovate/'.length)
          if (ref === 'configure') return
          const context = `renovate/${ref === 'reconfigure' ? 'configValidation' : 'artifacts'}`
          let success = null
          for (const data of (
            await github.rest.repos.listCommitStatusesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            })
          ).data) {
            if (data.context == context)
              console.log(data)
            if (data.context === context && !(success = data.status === 'success'))
                break
          }
          if (!success) core.setFailed('')
