name: Reovate commit status check
description: Checks renovate commit statuses
runs:
  using: composite
  steps:
    - if: startsWith(github.head_ref, 'renovate/')
      uses: actions/github-script@v9.0.0
      with:
        script: |
          const ref = context.payload.pull_request.head.ref
          const branch = ref.substring('renovate/'.length)
          if (branch === 'configure') return
          const name = `renovate/${branch === 'reconfigure' ? 'configValidation' : 'artifacts'}`
          const { statuses } = octokit.rest.repos.getCombinedStatusForRef({ ..context.repo, ref })
          let { state } = statuses.find({ context } => context == name)
          if (state != 'success') core.setFailed('')
