name: Reovate commit status check
description: Checks renovate commit statuses
runs:
  using: composite
  steps:
    - if: startsWith(github.head_ref, 'renovate/')
      uses: actions/github-script@v9.0.0
      with:
        script: |
          const { data } = await github.rest.repos.listCommitStatusesForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: github.sha
          })
          console.log(data)
          console.setFailed("testing")
          const regex = /^renovate\//
          for (const { context, state } of data)
            if (regex.test(context) && state !== 'success')
              core.setFailed(context)
