# This workflow is managed by gh actions-lock.

name: CI
on:
  merge_group:
    branches: [main]
  pull_request:
    branches: [main]
  push:
    branches: [main]
permissions: { }
jobs:
  git-check:
    permissions: { }
    uses: $/.github/workflows/git-check.yml
  pnpm-run-lint:
    permissions: { }
    uses: $/.github/workflows/pnpm-run-lint.yml
