# This workflow is managed by gh actions-lock.

name: CI
on:
  merge_group:
  pull_request:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
defaults:
  run:
    shell: sh
env:
  NODE_OPTIONS: >- # for v25.8
    --no-addons
    --disable-proto=delete
    --force-context-aware
    --force-node-api-uncaught-exceptions-policy
    --frozen-intrinsics
    --no-global-search-paths
    --pending-deprecation
    --tls-min-v1.3
permissions: {}
jobs:
  git-check:
    permissions:
      contents: read
    uses: $/.github/workflows/git-check.yml
  ci-success:
    if: always()
    needs:
      - git-check
    runs-on: ubuntu-slim
    timeout-minutes: 1
    steps:
      - parallel:
        - uses: $/.github/actions/renovate-status-check
        # https://github.com/orgs/community/discussions/45058#discussioncomment-7465690
        - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
          run: exit 1
