# This workflow is managed by gh actions-lock.

on:
  workflow_call:
defaults:
  run:
    shell: sh
env:
  NODE_OPTIONS: >- # for v25.8
    --no-addons
    --disable-proto=delete
    --force-context-aware
    --force-node-api-uncaught-exceptions-policy
    --frozen-intrinsics
    --no-global-search-paths
    --pending-deprecation
    --tls-min-v1.3
permissions: {}
jobs:
  # TODO prefer diffing tree over index
  git-check:
    permissions:
      contents: read
    timeout-minutes: 1
    runs-on: ubuntu-slim
    steps:
      - name: Configure git
        uses: $/.github/actions/git-configure
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          set-safe-directory: false
          sparse-checkout: '!/'
          sparse-checkout-cone-mode: false
          # replaces the default 'blob:none' none with the GitHub size limit:
          # https://docs.github.com/repositories/working-with-files/managing-large-files/about-large-files-on-github#file-size-limits
          filter: blob:limit=100m
      - parallel:
          - name: Check excludes
            # fails if any added items are ignored
            # todo review submodules
            shell: bash
            run: |-
              set -Cfuo posix
              export GIT_TEST_DISALLOW_ABBREVIATED_OPTIONS=true
              unset -v parent
              seterr () { return; }
              parent=$(exec git hash-object -t tree -- /dev/null)
              exec git diff-index -z --cached --name-only --diff-filter=A "${parent:?}" -- |
                  command -p xargs -r -0 -- git --literal-pathspecs ls-files -ci --exclude-standard -- |
                  {
                      unset -v -- path
                      while :; do
                          IFS= read -r -- path || case $? in (1) break;; (*) seterr; esac
                          >&2 command -p printf 'Adding ignored file %s\n' "${path:?}"
                          exit 150
                      done
                  }
          - name: Check whitespace attributes
            run: |-
              set -Cfu
              export GIT_TEST_DISALLOW_ABBREVIATED_OPTIONS=true
              unset -v parent
              parent=$(exec git hash-object -t tree -- /dev/null)
              exec git -c core.whitespace=tabwidth=1,indent_with_nontab diff-index --cached --check "${parent:?}" --
          - name: Check text attributes
            # What this does:
            # - forbids binary files with attribute text=true
            # - forbids non-binary files containing crlfs without attribute -text
            shell: bash
            run: |-
              set -Cfuo posix
              seterr () { return; }
              export GIT_TEST_DISALLOW_ABBREVIATED_OPTIONS=true
              unset -v parent
              parent=$(exec git hash-object -t tree -- /dev/null)
              exec git diff-index -z --cached --name-only --diff-filter=d "${parent:?}" -- |
                command -p xargs -r -0 -- git --literal-pathspecs ls-files -c --error-unmatch --format='.%(eolinfo:index)%x09.%(eolattr)%x09%(path)' -- |
                {
                    unset -v -- info attr path
                    while :; do
                        IFS=$'\t' read -r -- info attr path || case $? in (1) break;; (*) seterr; esac
                        info=${info#.}
                        case $info in ('') continue; esac
                        attr=${attr#.}
                        case $attr in (-text) continue; esac
                        case ${info:?} in
                            (lf|none) continue
                        ;;  (-text) case $attr in (''|text=auto*) continue; esac
                        esac
                        >&2 command -p printf "File with eolinfo '%s' and eolattr '%s': %s\\n" "${info:?}" "$attr" "${path:?}"
                        exit 150
                    done
                }
          - name: Check null char in text diff
            shell: bash
            run: |-
              set -Cfuo posix
              unset -v parent
              parent=$(exec git hash-object -t tree -- /dev/null)
              exec git diff-index --quiet --cached -G$'[^\x01-\xFF]' "${parent:?}" --
