# This workflow is managed by gh actions-lock.

# TODO: see if sparse checkout will compromise result
# TODO: see if git options affect grep

name: Git check
run-name: Checkint git attributes
on:
  workflow_call:
defaults:
  run:
    shell: sh
permissions: {}
jobs:
  # TODO use tree instead of index
  git-check:
    permissions:
      contents: read
    timeout-minutes: 1
    runs-on: ubuntu-slim
    steps:
      - uses: $/.github/actions/git-configure
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          set-safe-directory: false
          sparse-checkout: '!/'
          sparse-checkout-cone-mode: false
          # replaces the default 'blob:none' none with the GitHub size limit:
          # https://docs.github.com/repositories/working-with-files/managing-large-files/about-large-files-on-github#file-size-limits
          filter: blob:limit=100m
      - parallel:
          - name: Check whitespace attribute
            env:
              GIT_TEST_DISALLOW_ABBREVIATED_OPTIONS: true
            run: |
              set -Cfu
              unset -v parent
              parent=$(exec git hash-object -t tree -- /dev/null)
              exec git -c core.whitespace=tabwidth=1,indent_with_nontab diff-index --cached --check "${parent:?}" --
          - name: Check diff attributes
            shell: bash
            env:
              GIT_TEST_DISALLOW_ABBREVIATED_OPTIONS: true
            run: |
              set -Cfu -o posix
              command git grep --cached -qI -e $'[^\x01-\xFF]' -- || case $? in (1) exit 0;; (*) exit; esac
              >&2 command -p echo Null byte in text file.
              exit 1
          - name: Check excludes
            shell: bash
            env:
              GIT_TEST_DISALLOW_ABBREVIATED_OPTIONS: true
            run: |
              set -Cfu -o posix
              shopt -s lastpipe
              exec git ls-files -ci --exclude-standard -- | {
                  unset -v -- path
                  IFS= read -r path || case $? in (1) exit 0;; (*) exit; esac
                  >&2 command -p printf 'Ignored file: %s'\\n "${path:?}"
                  exit 1
              }
          - name: Check text attributes
            shell: bash
            env:
              GIT_TEST_DISALLOW_ABBREVIATED_OPTIONS: true
            run: |
              set -Cfu -o posix
              shopt -s lastpipe
              exec "${GIT_EXEC_PATH:?}"/git ls-files -c --format='.%(eolinfo:index)%x09.%(eolattr)%x09%(path)' -- | {
                  unset -v -- info attr path
                  while :; do
                      IFS=$'\t' read -r -- info attr path || case $? in (1) break;; (*) exit; esac
                      info=${info#.}
                      case $info in ('') continue; esac
                      attr=${attr#.}
                      case $attr in (-text) continue; esac
                      case ${info:?} in
                          (lf|none) continue
                      ;;  (-text) case $attr in (''|text=auto*) continue; esac
                      esac
                      command -p printf "File with eolinfo '%s' and eolattr '%s': %s"\\n "${info:?}" "$attr" "${path:?}"
                      exit 1
                  done
              }
