on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
defaults:
  run:
    shell: sh
env:
  DO_NOT_TRACK: 1
  NODE_OPTIONS: >- # for v25.8
    --no-addons
    --disable-proto=delete
    --force-context-aware
    --force-node-api-uncaught-exceptions-policy
    --frozen-intrinsics
    --no-global-search-paths
    --pending-deprecation
    --tls-min-v1.3
permissions: { }
jobs:
  # TODO prefer diffing tree over index
  actionlint:
    name: Lint github actions and workflows
    permissions:
      contents: read
    timeout-minutes: 1
    runs-on: ubuntu-slim
    steps:
      - name: Configure git
        uses: mestriga-org/public-workflows/.github/actions/git-configure@main
      - name: Checkout
        # TODO selective checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          set-safe-directory: false
          sparse-checkout: .github/workflows
      - name: Download and run actionlint
        # TODO new command syntax in release post 1.17: --command check --output-format github
        # TODO renovate update
        env:
          arg1: v1.17.0
          GH_TOKEN: ${{ github.token }}
        run: |
          set -- "$arg1"; unset -v arg1
          unset -v repo; readonly repo=kjanat/actionlint
          unset -v tempdir; tempdir=
          trap 'case $tempdir in ("") ;; (*) command -p rm -R -- "${tempdir:?}"; esac' EXIT
          tempdir=$(exec mktemp -d)
          command gh release -R "$repo" download --clobber -O "${tempdir:?}"/actionlint.tar.gz -p actionlint_*_linux_amd64.tar.gz -- "${1:?}"
          command gh release -R "$repo" verify-asset -- "${1:?}" "${tempdir:?}"/actionlint.tar.gz
          command tar -C "${tempdir:?}" -xzf "${tempdir:?}"/actionlint.tar.gz -- actionlint
          command -p rm -- "${tempdir:?}"/actionlint.tar.gz
          command "${tempdir:?}"/actionlint -color
