# This workflow is managed by gh actions-lock.

name: Renovate config validation
on: [workflow_call, workflow_dispatch]
defaults:
  run:
    shell: sh
permissions: {}
jobs:
  renovate-config-validate:
    permissions:
      contents: read
    timeout-minutes: 1
    runs-on: ubuntu-26.04
    steps:
      - uses: $/.github/actions/git-configure
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          set-safe-directory: false
          sparse-checkout-cone-mode: false
          # https://github.com/renovatebot/renovate/blob/42.42.0/lib/config/app-strings.ts#L1-L12
          sparse-checkout: |-
            /renovate.json
            /renovate.json5
            /.github/renovate.json
            /.github/renovate.json5
            /.gitlab/renovate.json
            /.gitlab/renovate.json5
            /.renovaterc
            /.renovaterc.json
            /.renovaterc.json5
            /package.json
            !*/
      - name: renovate-config-validator
        uses: docker://renovate/renovate:44.145.0@sha256:eabf9ee40d584cef407899037b03000f14cf9f19920e289fdf25cfde8972b78a
        with:
          # https://github.com/renovatebot/renovate/blob/42.42.0/lib/config-validator.ts
          entrypoint: renovate-config-validator
        env:
          NODE_OPTIONS: ${{ env.NODE_OPTIONS }} --no-frozen-intrinsics
