# This workflow is managed by gh actions-lock.

on: [workflow_call]
defaults:
  run:
    shell: sh
env:
  NODE_OPTIONS: >- # for v25.8
    --no-addons
    --disable-proto=delete
    --force-context-aware
    --force-node-api-uncaught-exceptions-policy
    --frozen-intrinsics
    --no-global-search-paths
    --pending-deprecation
    --tls-min-v1.3
permissions: {}
jobs:
  renovate-preset-validate:
    permissions:
      contents: read
    timeout-minutes: 1
    runs-on: ubuntu-26.04
    steps:
      - name: Configure git
        uses: $/.github/actions/git-configure
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          set-safe-directory: false
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /default.json
            /presets/
            !/presets/*
            /presets/*.json
            !*/
      - id: glob-presets
        # TODO handle files names containing double quotes and (possibly) escape chars
        run: |-
          set -Cfu
          # shellcheck disable=SC2120
          seterr() { return "$@"; }
          {
            command -p printf result=
            set +f; set -f -- presets/*.json
            case $# in (1)
              case $1 in (presets/\*.json)
                command -p test -f presets/\*.json ||
                  case $? in (1) set --;; (*) seterr; esac
              esac
            esac
            case $# in (0) ;; (*)
              case $* in (*'
          '*) seterr 1; esac
              command -p printf ' "%s"' "$@"
            esac
            command -p echo
          }>>"$GITHUB_OUTPUT"
      - uses: docker://renovate/renovate:44.132.1@sha256:70aea9310d45b93786db8cab3a91be1f2005fc3a73d805ff8fc9367ea170dfe0
        with:
          entrypoint: renovate-config-validator
          args: --strict --no-global -- default.json${{ steps.glob-presets.outputs.result }}
        env:
          NODE_OPTIONS: ${{ env.NODE_OPTIONS }} --addons --no-frozen-intrinsics
