on: [workflow_call]
defaults:
  run:
    shell: sh
env:
  NODE_OPTIONS: >- # for v25.8
    --no-addons
    --disable-proto=delete
    --force-context-aware
    --force-node-api-uncaught-exceptions-policy
    --frozen-intrinsics
    --no-global-search-paths
    --pending-deprecation
    --tls-min-v1.3
permissions: { }
jobs:
  renovate-inherited-config-validate:
    permissions:
      contents: read
    timeout-minutes: 1
    runs-on: ubuntu-26.04
    steps:
      - name: Configure git
        uses: $/.github/actions/git-configure
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          set-safe-directory: false
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /org-inherited-config.json
            !*/
      - uses: docker://renovate/renovate:44.125.1@sha256:1af51718ae09f3b7add4e7060038e533482a5fffda44564850bb59a95011491e
        with:
          entrypoint: renovate-config-validator
          args: --strict -- org-inherited-config.json
        env:
          NODE_OPTIONS: ${{ env.NODE_OPTIONS }} --addons --no-frozen-intrinsics
